# Generated by Django 5.2.14 on 2026-05-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_booking_duration_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('in_use', 'In Use'), ('completed', 'Completed'), ('returned', 'Returned'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='pending', max_length=20),
        ),
    ]
