# Generated by Django 5.2.14 on 2026-05-31 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_booking_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('in_use', 'In Use'), ('completed', 'Completed'), ('return_requested', 'Return Requested'), ('returned', 'Returned'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
