# Generated by Django 5.2.14 on 2026-06-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_equipmentimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='equipment_type',
            field=models.CharField(choices=[('tractor', 'Tractor'), ('harvester', 'Harvester'), ('rotavator', 'Rotavator'), ('cultivator', 'Cultivator'), ('plough', 'Plough'), ('seeder', 'Seeder'), ('sprayer', 'Sprayer'), ('thresher', 'Thresher'), ('trailer', 'Trailer'), ('water_tanker', 'Water Tanker'), ('power_tiller', 'Power Tiller'), ('baler', 'Baler'), ('transplanter', 'Rice Transplanter'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='last_service_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
